### ISSUE TITLE
Only targets .NET 7

### ISSUE THREAD

**Issue by ratsclub** [oskardudycz/Ogooreck#16]
I tried to use the library, however this requires .NET 7, while I'm using .NET 6. Are you open to relaxing the target a little bit?

**Comment by oskardudycz** [comment]
@ratsclub, sure if that stops you from using, I can release also .NET 6 version 🙂

**Comment by oskardudycz** [comment]
...aaand I’ve made it in 0.7.0 https://github.com/oskardudycz/Ogooreck/releases/tag/0.7.0 🙂

Feel free send feedback when you find anything odd 🙂

**Comment by ratsclub** [comment]
Thank you so much for the fast reply!
